version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/Lawnmower
   file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies_client.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy_client.sh
      timeout: 300
      runas: root